### ISSUE TITLE
MultiWorld

### ISSUE THREAD

**Issue by fabianobn** [otland/forgottenserver#100]
I'm asking for future interests!
I would say it will support?
Sincerely,

**Comment by gugahoa** [comment]
I plan to start researching about implementing multi-world support.
For anyone that already tried, could you share your experience, give tips and foreshadow about what I'm going to face?

@marksamman, if I start implementing it, would a PR be welcome?

I'm replying here mainly to ask for guidance and insight from anyone that already researched the topic before I start.
I'll tag some experienced contributtors, hope it's not too much of a bother. @ranisalt  @kornholi  @djarek

**Comment by BenDol** [comment]
Shouldn't multi world simply be done in separate databases with separate instances?

**Comment by ranisalt** [comment]
Yes. In my opinion, the login server and the game server should be separate (someone has already moved the login server out, I remember), then we wouldn't need to have much to change.

**Comment by marksamman** [comment]
I agree with @BenDol and @ranisalt. Each world should run in its own database. You would need a separate login server which either authenticates to all game servers databases (in which case people can use the same name on different worlds), or add a central database for the login server, which stores authentication data, character names and world_id. It's more of an infrastructure matter rather than something you can just implement in TFS, I don't think we'll merge any multi-world system into TFS itself, but you should work on a login server instead. For that reason I'll close this issue, but you may continue the discussion here if you'd like to.
