### ISSUE TITLE
onMove and onDropLoot

### ISSUE THREAD

**Issue by conde2** [otland/forgottenserver#1049]
onMove should be implemented for all creatures and will trigger when a creature moves 
Ex: `Creature:onMove(fromPosition, toPosition)`

returning false prevent the creature from move.

onDropLoot should be implemented for monsters and will trigger when a monsters drops some loot 
Ex: `Monster:onDropLoot(position, corpse, loot)`

maybe able to return a table with loot to be droped?
##

**Comment by Zbizu** [comment]
it can be done by onKill + addEvent (see my item stat system)
is there anything that prevents moving droploot to lua?

**Comment by gugahoa** [comment]
I moved monster drop loot to Lua on one of the servers I work on. My approach was implement Monster:onSpawn (it's a PR that wasn't merged) to register a onDeath event on every monster, the event called a MonsterType method that generate loot for the specified monster type and put the lut inside the corpse (arg of onDeath).

Since this onDeath event is triggered for every monster, maybe creating a Monster:onDeath would be cleaner?

@marksamman what do you think about this feature? Is it worth to send it as PR?

**Comment by andersonfaaria** [comment]
we are only pending monster onDropLoot to close this?

**Comment by Zbizu** [comment]
onMove: 
I propose "won't fix" label here because player movement is most often executed action. It would be very heavy to execute for the cpu. Workarounds like addEvent checking the player position, #2553 for blocking movement and movements exist to satisfy most common needs for movement check.

dropLoot: already finished
forgottenserver/data/scripts/eventcallbacks/monster/default_onDropLoot.lua
