### ISSUE TITLE
item:getPosition() and item:moveTo support for cylinder.

### ISSUE THREAD

**Issue by conde2** [otland/forgottenserver#1138]
As the title say, a way to get the item position inside a container and the possibility to move it.

**Comment by PrinterLUA** [comment]
You can use transform ^^?

**Comment by conde2** [comment]
What?
How can transform make possible to move an item from container X to container Y?

My specific problem, that i'm facing is that when using onMoveItem I can't check which container i'm moving for.

**Comment by marksamman** [comment]
Item.moveTo should definitely support moving to cylinders. This issue is mostly what blocked PR #762 from being merged. I'm not sure what you mean about get item position inside a container though. Can you explain your use case with that? One thing you could do is use getParent() to get the container of the item, iterate through all the items in the container and find the matching item to get its slot.

**Comment by conde2** [comment]
For example If a item is inside of a container the position should be:

{x = 65536, y = cylinderIndex?, z = slotPosition }

instead if I use: item:getPosition() inside a container it returns me the Tile position on the map.


The problem that i have is that i want to the player don't be able to move a item to inside a specific container, I can't use getParent() because the item is not inside of the container when i'm moving.
