### ISSUE TITLE
update to fucking newer client

### ISSUE THREAD

**Issue by rottyrubas** [otland/forgottenserver#1170]
sorry for mad tone my brothers. but i really would wish to see some newer clients.

**Comment by rottyrubas** [comment]
guess ill be forced to learn fucking brazol since tibiaking is 10x more active than dead otland

**Comment by kosicki123** [comment]
"Brazol"? TibiaKing is really more active, but you won't find any material to update your server there.
I can't understand what's the point on keep refactoring this version forever, tibia is already on 10.74, and we're stuck on 10.41...
It's mark really the only one on the world that can do this job? I wish I could have skills to this myself...
I know ShadowCores must be very profitable, but what's the point on holding us forever on 10.41? Release something at least 10.60...Your ShadowCores will keep safe and more updated than us...

Or maybe just put this thing to 10.74 and let's try to fix every bug we find...What's the point on use this git with pull requests and stuff if we can't even use the updated version of tibia...?

Well...this is my thoughts...

**Comment by luanlucian93** [comment]
I agree with friends above.

You get only updating the Shadowcores, but OTServ world loses when not release these updates to the public, it's a shame :(

**Comment by rowaraujo** [comment]
UPDATE PLEASE!
UPDATE TO 10.73!!

**Comment by marksamman** [comment]
This kind of tone is not welcome here. Feel free to fork the project and make the changes you're asking for, you may also submit a pull request once you're done. Nobody is being paid to work on this project so your demands are really off-putting. If this issue is important to you, and you aren't skilled enough to solve it yourself, you can put money where your mouth is by backing this issue: https://github.com/otland/forgottenserver/issues/887.
