### ISSUE TITLE
MoveCreature Client Crash

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1175]
Hello, i can confirm this error report. But me aswell have no idea how to reproduce this. I saw on my client_assertions reports and saw the same issue.

https://github.com/otland/forgottenserver/issues/885

**Comment by marksamman** [comment]
There's no point in keeping an open issue about it if there's nothing we can do to proceed. That's why the other issue was closed. Clients can submit arbitrary text as client assertions, it doesn't mean that the server did something wrong. It could be a client bug, it could be someone who has manipulated the client and triggered a client assertion. It could have been someone who was on another server, but submitted the client assertion to your server instead.

If you can provide steps on how to reproduce this issue, or if it becomes more common, please open a new issue with the new information you have gathered about it. If you don't have anything new to add, there's no point in opening an issue about it. You can also post in the old issue, we can re-open it if new information is provided that helps us at least confirm that the issue is caused by the server.

**Comment by StevenTrembly** [comment]
I got the same problem but more information proved here

https://otland.net/threads/movecreature-client-debug-with-all-information-proved.242954/
