### ISSUE TITLE
When or How we can Creature:setSpeed(value)?

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1235]
these conditions are very ugly things in tfs. And not sure can i set conditions on monsters.
What i want to do is change player and creature speeds trough scripts.

I don't find any simple setSpeed() option.
Will it come?
Is it possible to register that function to lua too?

**Comment by marksamman** [comment]
I don't see why you wouldn't be able to add conditions to monsters using Creature.addCondition, if it's not possible that's probably a bug and you should open a separate issue for that with instructions on how we can reproduce it.

There's no simple setSpeed() function because it's not that simple. What's speed exactly? Base speed? The effective speed? If the effective speed, what about active haste/paralyze conditions, what should happen when they expire, or should they just be removed when setSpeed is called? Should the new speed be saved so that it persists after logging out and logging in again (there's no speed column in the database at the moment)? These are all questions that will cause confusion, the simple solution is to use a speed condition.
