### ISSUE TITLE
Monster events

### ISSUE THREAD

**Issue by gugahoa** [otland/forgottenserver#1304]
@marksamman I would like to suggest reviewing #1067 as it's quite useful for registering creature events on every monster, just like an onLogin. There's others ways of using it that I'm sure people will think of.

If you would like, I can make a new PR for this, and move the onSpawn call from spawn::spawnMonster to game::internalPlaceCreature so it covers monsters created through Lua.

**Comment by marksamman** [comment]
If you're going to apply a creature event to every single monster, the event should be global instead of a creature event. If you want to apply it to a specific monster, I've already explained how you can do so in that issue. onSpawn **won't** be added. If you disagree, you're welcome to maintain a fork with that feature.

**Comment by gugahoa** [comment]
Well, that was only a example. As there can be a whole lot of other kinds of events. Let's say I want only to add a creature event to summons of a player that has a level over 50? Or want to add a creature event to every monster spawned between 18h and 19h. Monster:onSpawn that's what I think is appealing regarding this feature. If you could give me an answer as to how to do what I just talked about with today's source I would gladly drop the idea.

And I'm maintaining a fork with that feature, but thought it would be a good thing to add to TFS.
