### ISSUE TITLE
Question about Dispatcher

### ISSUE THREAD

**Issue by Nu77** [otland/forgottenserver#1312]
What is the real use of "g_game.map.clearSpectatorCache();" in Dispatcher ?

**Comment by djarek** [comment]
Clears the spectator cache (Captain Obvious to the rescue)? BTW When we're at it I wonder if it's at all worth actually caching spectators like that, since the cache is invalidated on every dispatcher cycle (and building it is actually quite a costly operation). If we were to make the map structures "flat" (i. e. apply Data Oriented Design by avoiding indirection) we could probably outperform the current system without caching.

**Comment by ranisalt** [comment]
Do you have any idea on how to do it, @djarek? I have sketched some stuff about making the map structure flat instead of a binary tree, and this would make the map loadable in sectors instead of its entirety, thus using much less memory when players are together.

**Comment by djarek** [comment]
IMO lazy loading of the map data is a bit of an overkill - it would add a lot of complexity for little benefit. The problem here is that we have to decide whether to optimize for memory usage or for performance, but that is a discussion that should be made in a separate issue.

**Comment by ranisalt** [comment]
Yes, I agree, that's just a possibility. I think the complexity (to understand, not programatically saying) of the map is already issue enough.

**Comment by djarek** [comment]
BTW I did a quick test and I couldn't determine whether there's a significant difference between caching spectators and not caching (i.e. the difference was smaller than "noise" caused by memory allocation).
