### ISSUE TITLE
Difference between binary storage and relational storage?

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#1342]
Well it has no title because github somehow is buggy.

My question is: what is the difference in performance from binary storage and relational storage?

Like inventory is saved as relational and map is saved as binary. Its just a matter of space in database?

**Comment by Luckey1729** [comment]
You'll probably get a better, more technical response from someone like Mark. But I think the gist of it is:

Binary storage is much more compact and is read/saved much faster than relational storage. How binary storage actually works is beyond my scope of knowledge (I'd *guess* that it has something to do with storing the tile items as bits, but I'm likely wrong.)

Relational storage used to save each item as a readable row, something like: (id, count). The save/load time for relational storage was **much** slower. Server save times could easily take minutes as opposed to a fraction of a second. 

TFS uses binary-tilebased iirc. That way if an item in a house becomes corrupted, only that tile gets wiped, as opposed to the entire house. It's still much faster than relational storage, but isn't was detrimental as straight binary storage.

**Comment by HeavenIsLost** [comment]
Thanks :)

**Comment by djarek** [comment]
In general, binary storage have some drawbacks - the binary representation of data might not be portable due to differences in endianness in hardware platforms and it's not very flexible, unless you design it with unused bits for future use.
@Luckey1729
You are actually correct, binary storage is achieved by serializing the objects into a "flat" data stream, usually by putting raw data there and using some way of preserving relationships between objects (you obviously can't just dump a pointer into the data stream).

**Comment by HeavenIsLost** [comment]
@djarek @marksamman even with this drawback, binary storage is faster?

**Comment by ranisalt** [comment]
Yes, endianness is a very rare problem since the vast majority of servers tend to use Xeon processors, and MySQL dumping and importing also treats this, and to upgrade database formats we have the migrations, and they can fix if something has to be rewritten. The drawbacks can be worked around, while the speed can not.
