### ISSUE TITLE
stairHop delay for spells/runes ?

### ISSUE THREAD

**Issue by gunzino** [otland/forgottenserver#1362]
Hello,

I would like to ask/report a problem about stairhopping. There is a variable in config.lua called stairJumpExhaustion. The problem is that the variable is checked in player.cpp when the player changes the Z coordinate of the position, than it will create condition_pacified for the player for the specified time.

Than the CONDITION_PACIFIED is checked only in the Player::doAttacking function a only apply when player attacks someone. I think the stairhop delay should be also applied for spells/runes. 

EDIT: I've checked the TFS 0.4 sources since I remember it was working on that and it used to create an exhaust for melee, spells and also created the CONDITION_PACIFIED.

addExhaust(ticks, EXHAUST_SPELLGROUP_ATTACK);
addExhaust(ticks, EXHAUST_MELEE);
if(Condition* condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_PACIFIED, ticks))
addCondition(condition);

If I am wrong, please close this and ignore. Thank you :)

**Comment by gunzino** [comment]
http://tibia.wikia.com/wiki/Updates/8.62:
PvP Stairhopping Delay: After changing floors, for example by going up or down ladders, you will be able to attack other player characters within the first 2 seconds, but only with single directed attacks. 

So the TFS using the opposite way allowing players to use Area spells instead of "single directed".

**Comment by marksamman** [comment]
There's no right or wrong if it isn't documented, we're not trying to copy the mechanics of any other game. We rather make features like this customizable so that the end-user can choose whether they want to it to work like you are suggesting, or as it currently works, but until we've managed to make that customizable in a good way (e.g. from a Lua callback, not adding another variable to config.lua) I rather leave the behavior as-is. For this kind of feature, onMove (#1188) sounds like the ideal Lua callback.

**Comment by peonso** [comment]
You can add this to spells

	function onCastSpell(cid, var)
		-- check for stairHop delay
		if not getCreatureCondition(cid, CONDITION_PACIFIED) then
			return doCombat(cid, combat, var)
		else
			return false
		end
	end

**Comment by gunzino** [comment]
Hello,

I've already fixed in in sources by adding cooldown on attack spells
