### ISSUE TITLE
Poisonous enemies poisoning at first hit

### ISSUE THREAD

**Issue by macevedoinf** [otland/forgottenserver#1372]
Like the title says, i tested with snakes and poison spiders and they poison at the first hit, even if they fail.
![screenshot_1](https://cloud.githubusercontent.com/assets/7191000/7763243/7f6e506c-0014-11e5-9f2e-549de29460ae.png)
##

**Comment by WibbenZ** [comment]
Confirmed
```
21:11 Your last visit was on Thu May 21 22:27:24 2015.
21:11 You are poisoned.
21:11 You are poisoned.
21:11 You lose 1 hitpoint due to an attack by a snake.
21:11 You are poisoned.
```

**Comment by EPuncker** [comment]
the condition system in monsters should be reworked to be more dynamic

**Comment by Alscara** [comment]
I've had this as well. Every hit by any poisonous creature results in being poisoned.

**Comment by jo3bingham** [comment]
If you trace a snake's attack you'll end up at the function [Combat::CombatHealthFunc()](https://github.com/otland/forgottenserver/blob/master/src/combat.cpp#L500). The first function call in this function is to [Game::combatBlockHit()](https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L3626). If you follow through the function you'll see that it always returns false because secondaryBlockType is always set to BLOCK_NONE. That means the if statement this function was called in will never be true, and thus will be stepped over. So, next it calls [Game::combatChangeHealth()](https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L3791). Again, if you follow through this function it will always return true [here](https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L3897) because healthChange is equal to 0. That means the if statement this function is called in will always be true, and, therefore, [Combat::CombatConditionFunc()](https://github.com/otland/forgottenserver/blob/master/src/combat.cpp#L536) will always be called, and this is the function that applies the poison condition to the player.

My suggestion is to simply return false if healthChange is equal to 0 because Game::combatChangeHealth() should only return true if the target's health was changed, and since 0 health change is applied it should return false. I've tested it and it does fix the issue, however, it could possibly cause issue with other functions that call this function. Though, I've looked and I don't see any reason it would, but I would like confirmation from @marksamman, or someone else who knows better, that this is fine.

**Comment by Alscara** [comment]
@jo3bingham I may misunderstand the way you've explained, but would your suggestion not limit it to only cause poison if the player takes damage? I see nothing wrong with that personally, and I know we aren't trying to mimic cipsoft, but I believe in their tibia, you can still get poisoned without taking damage, just not every time. Perhaps there should be a chance to poison whether taking damage or not from the attack. Just playing the devil's advocate here :p

**Comment by jo3bingham** [comment]
@Alscara I haven't played Tibia in many years, so my memory isn't the best. You're probably right that poisoning isn't limited to damage only, but a random chance regardless if the attack was blocked or not.
