### ISSUE TITLE
Guild Rank bug when have more than 3 different ranks

### ISSUE THREAD

**Issue by sircurse** [otland/forgottenserver#1436]
I noticed that I have a bug on my guild rank, what happens:

If I have more than 1 guild rank (names) for the same level access, it will show on your player the first created rank, for instance:

ID ---- Guild ID ---------- RANK ---------- LEVEL
1 ----- 7 ------------------- 3 -------------- Owner
2 ----- 7 ------------------- 2 -------------- Sub-owner
3 ----- 7 ------------------- 1 -------------- Sorcerer rank
4 ----- 7 ------------------- 1 -------------- Paladin rank
5 ----- 7 ------------------- 1 -------------- Druid rank
6 ----- 7 ------------------- 1 -------------- Knight rank

What happens is that all players in ranks after "Sorcerer rank" will appear ingame as "Sorcerer Rank".
Someone have noticed it? There is any fix for that?

**Comment by ranisalt** [comment]
I can verify that. A player hols the level of its rank instead of the ID, and shows the first rank that has that same level when looked at. References:

https://github.com/otland/forgottenserver/blob/master/src/guild.cpp#L45-L63
https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L274
https://github.com/otland/forgottenserver/blob/master/src/player.h#L1285

I'll have a look at that when I have spare time.

**Comment by ranisalt** [comment]
I think your problem is that no 2 ranks should have the same level. What are you using to manage your guild and create the ranks?

**Comment by sircurse** [comment]
Hi Ranieri,

I m using Gesior for TFS 1.0.
But what issue can cause the account manager if the issue that I can see is
in-game? I mean... I have all the ranks set correctly on my DB, don't?

For instance, I would like to add 10 different groups of members, all those
goups should have the same access level (member only), the game itself will
recognize the frist group ID from all that have the same level, and will
keep the name of this ID for all other groups, even with a different ID
when you use look on character, it answers as the name of the very first
group created for member access only.

Can you show me the guilds tables that you used to test?



Curse.



________________________________________________


*Network Consultant*
*Anderson Pereira* (anderson@progmass.com)
*Phone*:  +55 11 2053-0911 / *Mobile*:  +55 11 9-8261-2839

[image: View Anderson Pereira's profile on LinkedIn]
<http://br.linkedin.com/in/andersonredes>





2015-07-04 2:55 GMT-03:00 Ranieri Althoff <notifications@github.com>:

**Comment by ranisalt** [comment]
Well, no, actually.

There's nothing that enforces that guild levels can be only 1, 2 or 3. Each guild rank *should have a different level* and that's where you are having problems. If you want 10 groups, then number them from 10 to 1, and the highest one is the leader rank. To be specific, the guild level is an 8-bit unsigned integer, meaning you can have levels from 0 to 255.

This is a flaw in Gesior, which probably didn't read the server code and assumed leaders are 3, vice-leaders are 2, and normal members are level 1, but that simply isn't true, as I just explained. You can either fix in Gesior, by prohibiting different ranks to have the same level (you can enforce it with an UNIQUE key in the table) or on the server, by storing the rank ID instead of the rank LEVEL on the player.

What do you prefer? I can patch the server if you don't want to mess with your account manager.

**Comment by ranisalt** [comment]
Yeah, that's it. Guild ranks are actually limited to only 3. I'm trying to modify it and allow as many as you want.

**Comment by ranisalt** [comment]
Here, please try to merge this branch: https://github.com/ranisalt/forgottenserver/tree/fix-player-guild

Players now store their rank instead of their rank level, and there is no more the hard limit of 3 guild ranks. Please keep in mind that the Lua function `player:setGuildLevel` is not reliable anymore. There are no changes in database needed.

From what I could test, at least look is working fine and everything is still working the same:
![Imgur](http://i.imgur.com/SiBg2eo.png)

**Comment by sircurse** [comment]
Thank you Ranieri,

Just tested it and worked great, as I don't use in-game management I wont
need that function so it is ok.

Should it be pointed as a fix to master?



Thank you again,
Curse.

________________________________________________


*Network Consultant*
*Anderson Pereira* (anderson@progmass.com)
*Phone*:  +55 11 2053-0911 / *Mobile*:  +55 11 9-8261-2839

[image: View Anderson Pereira's profile on LinkedIn]
<http://br.linkedin.com/in/andersonredes>





2015-07-08 1:21 GMT-03:00 Ranieri Althoff <notifications@github.com>:

**Comment by ranisalt** [comment]
Yes, I will prepare a pull request for it.
