### ISSUE TITLE
How to bypass header decoding for different protocol

### ISSUE THREAD

**Issue by ranisalt** [otland/forgottenserver#1499]
Hello all,

I'm working on a HTTP protocol but I'm having a big time dealing with how connection works on TFS. Something in the `Connection` is aborting the message even before it gets to new `ProtocolHttp::onRecvFirstMessage`, and I can't even read messages that come via HTTP protocol port.

I'm not sure where to start tackling this problem. I think the connection stack just assumes every message comes from and goes to the client, thus it tries to read the first half word to get the message lenght and, as I'm trying to do a HTTP GET, it reads the `GE` in little endian mode. I tracked with a debugger ever since `ServicePort::onAccept` and this indeed happens.

I have modified the function `ServicePort::onAccept` and added:
```
if (service->get_protocol_identifier() == 0x80) {
	std::cout << "HTTP protocol" << std::endl;
}
```
Just to try out, and I think this does the trick, but I don't really understand in full what the `Connection::accept` methods do and if I can bypass them.

I'd rather not mess with the connection stack, but I think that is the only way. Someone can give me a light?

**Comment by djarek** [comment]
The networking stack assumes that the packet contains a length at the very beginning so you'd need to rework it to accept 2 types of incoming messages (trust me, you don't want to do it).
To be honest, I really don't like the idea of having an HTTP service in the server. IMO from a design point of view, it would be a lot better to design a very simple protocol that communicates with a HTTP backend. It doesn't have to be fancy, use a packet length and just dump/accept JSON/XML in there.

**Comment by ranisalt** [comment]
Hmm actually this is a really great idea, the only problem is that we would have the very first JSON API that does not work with HTTP and requires a separate server, but indeed it would simplify everything a lot.

**Comment by djarek** [comment]
Actually we would not be the first as some companies use custom binary protocols to feed data or retrieve statistics to/from the user-facing servers. You don't hear about these solutions because they're employed internally at Google, Dropbox etc, though they use it for scalability, rather than simplicity of design (though the latter also occurs, thanks to Separation of Concerns).

A great side effect of this is that we allow a lot of flexibility and make some problems trivial (not that I doubt in your programming skills and determination, but what are the chances of you getting TLS right in the server on the first attempt without serious bugs?).

A few tips for writing protocol objects:
-Connections are volatile and can go away at any time, unless you hold a shared_ptr to them, also don't assume too much about their state
-Remember to set the encryption and hash enabling flags (inherited from Protocol)
-Protocols are objects touched by at least 2 threads, so try to avoid state
-If you use state, make sure that it's either protected by a mutex or read only
-If there are methods that are only allowed to be touched by the dispatcher, specify that in a comment, trust me, it helps
-Don't access ANY game state outside the dispatcher thread

**Comment by ranisalt** [comment]
I will take your advice on it as I like the network stack simplicity, and I prefer not to dwell on implementing the HTTP protocol.
