### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1515]
Hello, i just wonder what do you mean rewrite lua npc system and lua scripts for quest. If you can be more elaborate, i may can help.

**Comment by WibbenZ** [comment]
Read somewhere that the changes should not ruin backwards compatability.
So most likely.. either compile the userdata from cid as we do in some locations or... add all the files to compat.lua and rewrite most of it using userdata from the start.

The Lua scripts for quests can be found here; #1064

**Comment by marksamman** [comment]
Rewriting the NPC system means rewriting the NPC system to utilize userdata objects more efficiently and maintaining backwards compatibility.
Lua scripts for the quest log means you should be able to customize the quest log using Lua instead of being restricted to what can currently be done in the XML file. See #1064 for the discussion.
