### ISSUE TITLE
db.asyncStoreQuery is crashing the server

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#1533]
the function asyncStoreQuery work just fine, the problem happens when there is any lua error inside the callback.

Code to crash the server(very simple):

http://hastebin.com/obiseweroc.lua

Visual Studio 2013 debug print(with callstack):

http://prntscr.com/86zmya

Hope @marksamman can fix it.

@djarek check this too :+1:

**Comment by djarek** [comment]
Unable to reproduce. Are you running unmodified master?

**Comment by HeavenIsLost** [comment]
Yeah, thanks @djarek for confirming it :)

Right now the walk around is using pcall to call another function that will deal with the database result. At least if there is any errors the server will not crash and i can see the lua error.

Does pcall have overheads? can it kill the performance gain we had using db.asyncStoreQuery?

**Comment by djarek** [comment]
pcall does have an overhead (errors are stored), but we're already using pcall to call the callback anyway.

**Comment by djarek** [comment]
Not sure if it's the cause here, but shouldn't we store the callback reference in the lua registry so that it can be then called once the query finishes? Events' callbacks seem to work like that and it seems that it is the problem here (the error just before the crash is "attempt to call a thread value").
