### ISSUE TITLE
Not rly an Issue

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1583]
Why aren't player:say() and player:sendTextMessage() consistent?
On firs the text color is on 2nd line. on second its on first line.

**Comment by WibbenZ** [comment]
You can check the logs and see who moved those functions and ask.
The only reason I can think of is to keep it as it was, to ease the move from the legacy interface to the new one.

But at the same time it would have been good to do them the same way, even adding a default color on them(IMO).
You can make a PR and see if Mark approves it, most likely not since it's hard to make a compat function for it that isen't always getting checked (you can ofc just run the check in each function, but that will add more overhead).

**Comment by marksamman** [comment]
Because they're different functions and we didn't think much about the ordering of parameters in different functions when we started working on the new Lua API. I don't think it's such a big deal that we should change it now.
