### ISSUE TITLE
Using math.random() in addDamage always generates the same value after first spell execution

### ISSUE THREAD

**Issue by raymondtfr** [otland/forgottenserver#1625]
If I do:

``` lua
condition:addDamage(1, 5000, -math.random(1, 10))
```

it gives a random number at the first time I execute the spell, but afterwards it keeps giving the same random value, it really doesn't randomize.
If I do `/reload spells` it does give another value.

I have tested this with latest nightly build.

**Comment by diath** [comment]
That's expected behavior since you're basically assigning the result of math.random.

**Comment by LuigiLazzari** [comment]
You need to run math.randomseed() once before using math.random(), like this:
```lua
math.randomseed(os.time())
```
One possible problem is that the first number may not be so "randomized" in some platforms. So a better solution is to pop some random number before using them for real:
```lua
math.randomseed(os.time())
math.random(); math.random(); math.random()
```

**Comment by ranisalt** [comment]
@LuigiLazzari your statement is false. "Popping some random number" does not increase randomness as the sequence is always the same, you just shift it forward by a constant number of times.

And IIRC the engine already seeds the (pseudo) random number generator, so it is not needed to seed it again on the script, it would just reduce the randomness as the number of numbers popped would be reset, instead of increasing from every single use of math random on the entire server.

**Comment by raymondtfr** [comment]
@diath I think I got a grasp of what you said. But then I also made some functions calls to generate random  values but it won't randomize.
@LuigiLazzari That's the second thing I tried, but it seems to me that diath is right, I guess I can't think of anything else to fix it lol. Could this be ``enhanced`` in C++? (reset addDamage values each different spell execution)?

**Comment by gugahoa** [comment]
You're calling :addDamage only one time, that's when you're loading spells. To make it truly random, you need to assign :addDamage every time the spell is cast (onCast),

It's not an issue with the source, but with how you're doing the script.

**Comment by kornholi** [comment]
Right, can't you just do something like this?

```lua
local combat = Combat()
combat:setParameter(...)

function onCastSpell(creature, var)
        local condition = Condition(...)
        condition:addDamage(1, 5000, -math.random(1, 10))

        combat:setCondition(condition)

	return combat:execute(creature, var)
end
```

I'm not sure if creating new conditions on cast would cause any performance issues.

**Comment by raymondtfr** [comment]
Weird, it did work a few times but then it gives the same value over and over. (even setting randomseed);

**Comment by ranisalt** [comment]
No, it's not a leak, it's because you are adding a damage but not removing the previous. You need to do a copy of the combat, then add the damage and execute. Try:

```lua
local combat = Combat()
combat:setParameter(...)

function onCastSpell(creature, var)
    local condition = Condition(...)
    condition:addDamage(1, 5000, -math.random(1, 10))

    local newCombat = {}
    for k, v in pairs(t) do newCombat[k] = v end
    setmetatable(newCombat, getmetatable(combat))
    newCombat:setCondition(condition)

    return newCombat:execute(creature, var)
end
```

**Comment by mazen-mardini** [comment]
There should be a customized random function that actually has a proper seed (that isn't based on something predictable such as time).

**Comment by marksamman** [comment]
You can seed math.random with data from /dev/urandom if the output from your RNG is sensitive, or not use math.random at all and just read from /dev/urandom if you want a CSPRNG. This issue is completely unrelated to that though, this has nothing to do with the RNG being predictable, the problem here is that a value from the RNG is generated once and reused for every execution of the spell. The seed used in TFS is completely fine for most purposes.

**Comment by mazen-mardini** [comment]
@marksamman , it's not hard to implement a function that enables proper randomization that would also be useful for security purposes. Just because this issue only covers spells, doesn't mean we can't generalize the problem and consequently solve a lot of (future) issues with only a little effort.

**Comment by marksamman** [comment]
What does "proper randomization" even mean? It's not a trivial task to implement a true RNG. A CSPRNG is still a PRNG and given its entropy source, it is also predictable (math.randomseed in Lua calls srand, meaning that your seed is truncated to unsigned int, so you would have to override the implementation of math.random and math.randomseed so that math.randomseed still works for those that depend on a deterministic RNG).

Don't get me wrong, I'm not saying that using a CSPRNG is bad, it's actually good if you can get it right and your application needs it, and it's definitely stronger than a PRNG seeded with time data. What I'm saying is that os.mtime() with a PRNG is good enough for how math.random() is used in TFS, you would potentially introduce new problems out of something that nobody has ever had a problem with for over 10 years with TFS.

If you think it's "not hard" to properly implement a CSPRNG that works with arbitrary ranges, please go ahead and I'll help you understand the challenges by pointing out the flaws in your code (unless you're an expert in this field, in which case I'll be happy to merge your pull request, but I won't be implementing it myself because there are far more important issues to work on). This issue has nothing to do with RNG at all FWIW, so if you want to carry this discussion on, please do so with your pull request.

**Comment by mazen-mardini** [comment]
I never ordered you to implement an RNG from scratch. I just offered a potential solution to the project that would (at its core) be easily done and that would be suitable for most thinkable use-cases.

Furthermore, I don't have time to create a pull request, as that would require me to actually integrate the solution into otserv (which I'm sure would be technically possible) and that would take more time. But I'll still offer a solution, which is the following:

``` cpp
#include <boost/thread.hpp>
#include <boost/random/random_device.hpp>

unsigned int cust_random() {
	static boost::thread_specific_ptr<boost::random::random_device> gen;
	
	if (!gen.get())
		gen.reset(new boost::random::random_device);
	
	return (*gen.get())();
}
```

**It is:**
- Small.
- Thread-safe (works with std::thread too).
- A CSPRNG.
- Cross-platform.

It looks good to me, but if you can find anything wrong with it, the feedback is still of course be appreciated.

**Comment by marksamman** [comment]
It doesn't work with specified ranges.

**Comment by mazen-mardini** [comment]
I have better things to do than to argue with you, and even if it was the case I wouldn't have written that "code snippet". That "code snippet" wasn't even for you to begin with as I've already noted that you're uninterested in solving this problem yourself. It was for any developer willing to implement proper randomization that is suitable for security purposes. And btw, this is not a replacement of math.random, where did you get that from? I thought it was quite clear that it wasn't (it didn't even take any arguments). This is a way to acquire a secure random number, nothing more, and on top of it you can implement something like math.random.

If you don't want this in this issue then fine.

For anyone who is interested: Regarding the code. There is a problem indeed, but the problem was not exclusively that it generated a uint, but that each platform have their own min and max values. To fix this you'd have to use random_device::min() and random_device::max(), and with those generate/return a double that does have a consistent min- and max-value across all platforms. 

I'd like to see this implemented, and not just some timestamp-based solution to fix bugs like these. If anyone other than myself is interested and capable of integrating this into otserv then please message me and I'll help you out if you need.

**Comment by ranisalt** [comment]
Could you please share an example on how it's really needed to have CSPRNG on Lua? I'd happily implement it if there's a good case.

**Comment by marksamman** [comment]
> I have better things to do than to argue with you

It doesn't seem like it. You're obviously not interested in contributing to the project because of your time constraints, yet you have time to write off-topic comments and claim that you're sharing code with people who are interested in a CSPRNG in an issue that has nothing to do with RNGs.

You started posting an off-topic comment in this issue, and even in your latest comment you initially wrote "just some timestamp-based solution to fix bugs like these" before you rescinded it, which proves that you still thought this was a RNG/time-seed related bug after I had already told you **three times** that it wasn't.

If you, or @ranisalt, want to continue this discussion and neither of you want to open a pull request, at least open a new issue for it if you have reason to believe a CSPRNG is suitable anywhere in our code base, because this discussion is unrelated to this issue.

**Comment by asamy45** [comment]
@mazen-mardini I like the thread-safe approach, why don't we implement something more complex, e.g. make sure we call `sched_yield()` just before?

**Comment by ranisalt** [comment]
> @mazen-mardini I like the thread-safe approach, why don't we implement something more complex, e.g. make sure we call sched_yield() just before?

> at least open a new issue for it

Let's move on

**Comment by marmichalski** [comment]
@ranisalt / @raymondtfr could this be closed? There is nothing to do here and the discussion is not even on topic.

Unless you want to introduce new method(s) to manage condition damage list, like `condition:clearDamageList`. Then the onCast example could be:
```lua
local combat = Combat()
combat:setParameter(...)

function onCastSpell(creature, var)
    local condition = Condition(...)
    condition:clearDamageList()
    condition:addDamage(1, 5000, -math.random(1, 10))

    combat:setCondition(condition)

    return combat:execute(creature, var)
end
```

or add an optional argument to `condition:addDamage`, `addDamage(rounds, time, value, reset/clear/prune/whatever-is-suitable = false)`
