### ISSUE TITLE
mission vocation info on runes

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#1634]
global:
You see a paralyse rune.
It can only be used by druids with level 54 and magic level 18 or higher.
It weighs 2.10 oz.

tfs:
You see a paralyze rune ("adana ani"). It can only be used with level 54 and magic level 18 or higher.
It weighs 2.10 oz.

**Comment by slavidodo** [comment]
<h3>There are two ways to fix this.</h3>
Making xml attribute &lt;attribute vocation="vocname"/>
Or importing rune information from spells.xml as vocation are mentioned there.

**Comment by marksamman** [comment]
The solution to this would be to use the information from spells.xml.

**Comment by ranisalt** [comment]
> The solution to this would be to use the information from spells.xml.

Agreed, no need to duplicate data. I've already started looking at how to do it.

**Comment by slavidodo** [comment]
### Solution

Sorry for late answer, refer to ```item.cpp```
```c++
#include <boost/algorithm/string.hpp>

extern Spells* g_spells;
extern Vocations g_vocations;
```

Replacing https://github.com/otland/forgottenserver/blob/master/src/item.cpp#L828-L829 with :

```c++
s << ". " << (it.stackable && tmpSubType > 1 ? "They" : "It") << " can only be used";

auto vocMap = g_spells->getRuneSpell(it.id)->getVocMap();
auto promotedVocMap = g_spells->getRuneSpell(it.id)->getVocMap();
const int32_t mp = vocMap.size();
int32_t y = static_cast<int32_t>(mp);
if (mp > 0) {
	s << " by ";
	for (int32_t i = 0; i <= 8; ++i) {
		if (vocMap[i] && vocMap[i] == true) {
			Vocation* voc = g_vocations.getVocation(i);
			if (voc && voc->getId() <= 4) {
				std::string vocName = voc->getVocName();
				boost::algorithm::to_lower(vocName);
				s << (mp != y ? " and " : "") << vocName << "s";
				y -= 1;
			}
		}
	}
}

s << " with";
```

@marksamman Take a look on the code, I tested for first time and worked fine.

**Comment by ranisalt** [comment]
> if (voc && voc->getId() <= 4) {
It hardcodes a quantity of vocations, which is probably a bad idea since vocations are configurable too.

**Comment by marksamman** [comment]
I appreciate that you're trying, but that code is not good enough. What's the point of promotedVocMap, and why are you calling getRuneSpell with the same argument twice? Why are you copying the map instead of holding a reference to it? The vocation map should probably be changed into a set too, but that's not a fault in your code. The hardcoded magic numbers should be avoided too, there are proper ways to check if a vocation is a promotion. I also don't think we need to use boost::algorithm unless it offers any significant advantages over the functions we currently have in tools.cpp, and if it does have any advantages, we should just update our tools.cpp implementation and still make use of it.

**Comment by slavidodo** [comment]
@ranisalt Totally forget that point, thanks.
@marksamman There was no reason why I cloned promotedVocMap as it's not used, thanks for the note. For the use of ```boost::algorithm```, I didn't look so much at the project so that i just imported it and I agree with you there is no difference between the use of it and the use of the function you have in tools.cpp

Firstly : I found many unused xml attribute in spells.xml ( showInDesc..),
If you agree with me there was no reason to add the promoted vocation to the node but this will require rework the weapons and spells < casting spells and runes >.

Another thing in ```vocations.h```, Is there any reason why you make vocationsMap private, Why it would be very useful here instead of making a public function to call it.

Thanks, I will edit the code for now, tell I rework it.

**Comment by ranisalt** [comment]
> Firstly : I found many unused xml attribute in spells.xml ( showInDesc..),

`showInDescription` is exactly what is wanted in this PR, by the way :stuck_out_tongue_closed_eyes:

**Comment by marksamman** [comment]
Making data members private is a common practice in OOP. You should work with classes by calling methods, not by directly accessing or mutating their internals/implementation details.

**Comment by slavidodo** [comment]
@marksamman Updated the main code I posted.

**Comment by ranisalt** [comment]
> Making data members private is a common practice in OOP. You should work with classes by calling methods, not by directly accessing or mutating their internals/implementation details.

Account class deserves own methods, then: https://github.com/otland/forgottenserver/blob/master/src/account.h

**Comment by slavidodo** [comment]
I don't agree with that.

**Comment by marksamman** [comment]
The boolean in vocationMap should indicate whether or not to show in description, instead of always being true. That way, you can remove your vocDescMap. If you really want to contribute, I suggest you open up a pull request so that it will be easier for me to comment on your code. There are still a couple of oddities in your code.

@ranisalt Account is not an ordinary class, it's just a struct so we can bundle the variables that describe an Account as a single type. It's perfectly fine as-is. We try to follow OOP guidelines where it makes sense, but in this case I have to disagree with you.

**Comment by ranisalt** [comment]
IIRC structs in C++ are plain public classes, nothing less, nothing more, despite old semantics from C. But I do agree that it is perfect as it is, and that makes much more simple to use, let's not enter into that matter.
