### ISSUE TITLE
normal_random(int32_t minNumber, int32_t maxNumber)

### ISSUE THREAD

**Issue by conde2** [otland/forgottenserver#1696]
This function never return the maxNumber

For example:
A random number between 1 and 3 will never result in 3

The function is returning a random number between minNumber and (maxNumber - 1)

**Comment by ranisalt** [comment]
Well that's what random generators do, they pick in the interval [min, max)

**Comment by conde2** [comment]
The interval is being returned like that
[a, b[

But shouldn't it return [a,b] ? Like a math.random from Lua?

**Comment by marksamman** [comment]
It can return 3, however, it should return 2 most of the times, but for some reason it returns 1 most of the time (could be because it's rounding down). I'll see if this can be improved. The chance for it to return 3 should be equal to the chance of it returning 1. If you want uniform randomness, use uniform_random.

**Comment by marksamman** [comment]
It should be working properly for the range [1,3] now.

Before b7a02ab030a34c971c0031ad930a19fb5dcab18d:
1: 25002860
2: 23860811
3: 1136329

After b7a02ab030a34c971c0031ad930a19fb5dcab18d:
1: 7934069
2: 34132159
3: 7933772
