### ISSUE TITLE
Protection zone from stairs!

### ISSUE THREAD

**Issue by slavidodo** [otland/forgottenserver#1784]
Well, within very pure sources ( only 10.90 initialization )

You can enter stairs ( which leads to protection zone ) from non-protection zone with pzLocked normaly!!

-- Picture!
![Image](https://i.gyazo.com/4788e798fe246ef789e6f43c216b3ad2.gif)

--- EDIT ---

The solution of making the tile of stair itself protected is very basic. However we should implement it in `queryAdd` of the tile!

**Comment by wgrriffel** [comment]
as I said at #1766, imo it is not an issue because if you don't want it, do it like cipsoft does surround level changes with PZ, but as Samman apparently want this fixed because #1766 was marked with an enchant, so I think this can wait until roadmap onStepIn/onStepOut return value that matter and fix this through lua.

**Comment by PrinterLUA** [comment]
As you metioned, you need to put protection zone om the stair. As for ladder we have to make changes in the lua file.

**Comment by marksamman** [comment]
This is working as intended.

**Comment by wgrriffel** [comment]
@marksamman Why this is working as intended but #1766 is not? Seens like same thing.

**Comment by marksamman** [comment]
This can easily be solved with the expected behavior by placing protection zone on the stair. The same thing can not be said about ladders, because you need to place protection zone on a 3x3 area to make sure it can't be used with PZ lock, and in some cases you may want the player to be able to move within that 3x3 area even if they have PZ lock, just not be able to climb it. Stairs are also implemented in the source code, and changing queryAdd to check protection zone of the destination tile may have undesired side effects. Updating a ladder script is much simpler.
