### ISSUE TITLE
Question about protocols.

### ISSUE THREAD

**Issue by slavidodo** [otland/forgottenserver#1847]
Why don't we put `parsePacket` in dispatcher thread? This will clear the code a bit actually, instead of adding game tasks everywhere.

**Comment by HeavenIsLost** [comment]
The current packet parser code(parseSay, parseThrow, etc) runs under asio thread, then it add the game tasks like you said. Its removes a bit of the burden from the dispatcher thread. Another thing, pay attention to addGameTaskTimed and addGameTask when adding the game tasks to the dispatcher. The dispatcher works better with smaller tasks imagine. Smaller tasks make the dispatcher execute a little bit of everything, making the perception of everything being executed at the same time(for the players) more fluid.

**Comment by slavidodo** [comment]
it's the same idea actually, 99% of all packets are passing their results to dispatcher thread for game function... Which is the same idea if we put game function in a single-thread and parsePacket in the multi-thread.

**Comment by slavidodo** [comment]
@marksamman What's your opinion?

**Comment by marksamman** [comment]
I haven't looked into it yet, but it may fix some potential race conditions in parsePacket, although as @HeavenIsLost says some packets are dispatched with addGameTaskTimed, which means that they're dropped if they're not processed fast enough (because they're less important than other packets), which would happen under heavy load on the dispatcher.
