### ISSUE TITLE
SetConsoleCtrlHandler

### ISSUE THREAD

**Issue by jo3bingham** [otland/forgottenserver#1853]
https://github.com/otland/forgottenserver/blob/master/src/otserv.cpp#L98
### Steps to reproduce (include any configuration/script required to reproduce)
1. Log off or shut down
### Expected behavior

TFS should save and shutdown as if you had closed the console window.
### Actual behavior

TFS shuts down without saving.
From my tests it seems as though the function does not fire when a user logs off or does a shutdown, only when closing the console.
### Environment

Windows

**Comment by EvilHero90** [comment]
#1277 already adressed that issue there, Mark wants to wait until signal handling is fully done.

**Comment by marksamman** [comment]
It doesn't sound like the same issue, @jo3bingham is reporting that the SetConsoleCtrlHandler callback isn't called at all on Windows log off/shutdown.

**Comment by asamy** [comment]
That code is calling .stop() on all threads inside a dispatcher thread and calling `ExitThread` right after adding the task, you expect this code to really even execute?

**Comment by djarek** [comment]
I'm wondering, does this issue still persist? We no longer have the ```SetConsoleCtrlHandler``` function in 1.3

**Comment by wgrriffel** [comment]
@djarek SetConsoleCtrlHandler are a function from Windows api, it was removed when you introduced handling for posix signals, which make even worse for Windows users, now we are completly ignoring Windows, (we only handle posix signals that windows supports, which is INT and ABRT), even SetConsoleCtrlHandler are deprecated for this issue, it doesn't solve the problem for Windows 7(server 2008)  or better, shutdown and log off event are not been dispatched anymore as a CTRL event, so if you care about windows, you should consider spliting entry points in order to get windows events/signals, tbh idk how much you guys care about windows, since majority runs the server under linux

**Comment by djarek** [comment]
Isn't this the case of "Doctor, doctor, it hurts when I hit myself with a hammer."? If someone cares about server saves on server shutdown, they should use the Windows Service Management (or w/e it's called). Not sure if we're compatible with that, but if we're not, we probably should work on that, rather than create weird workarounds.

**Comment by wgrriffel** [comment]
i think you meant is Windows Task Scheduler, and no, it doesn't support directly sigint and sigabrt (only way you could make it saves before shutdown with windows), spliting entry points are not a workaround, it's how windows works, literally windows entry point are WinMain not standard C lib main, it's where windows can input things, if you want you can still make workarounds to get these inputs, but we would need one more workaround to get it working, since SetConsoleCtrlHandler doesn't get end session query from OS anymore, we would need to craete a dummy hidden window just for that purpose, because linker set main as "terminal app", which also can't get messages from system, in both cases would looks weird, i doubt anyone hosts a server with windows, that is why i asked if we should care about it.

**Comment by djarek** [comment]
I meant making TFS a Windows NT [service](https://code.msdn.microsoft.com/windowsapps/CppWindowsService-cacf4948).

**Comment by wgrriffel** [comment]
Windows services are most for drivers and background updaters, even if we support it, wouldn't fix this issue, only way windows give you a chance to do something before it releases your application on shutdown is handling [end session](https://msdn.microsoft.com/en-us/library/windows/desktop/aa376889(v=vs.85).aspx) message.

**Comment by djarek** [comment]
OK, so unless there's more demand for this feature we will leave this as it is. I'm closing this issue.
