### ISSUE TITLE
Game.createItem should allow creation of items even if there are no tiles available

### ISSUE THREAD

**Issue by TwistedScorpio** [otland/forgottenserver#1892]
Isn't bad that basically [Game.createItem](https://github.com/otland/forgottenserver/blob/master/src/luascript.cpp#L4284) currently does not allow the creation of an item in a position if there is no tile available? There's no allowance to create bridges due to this small issue.

**Comment by gugahoa** [comment]
If there's no tile, who'll be the parent of the item?
You could always verify if there's a tile before calling Game.createItem, if there is not, then create a tile there. (Game.createTile)

**Comment by ranisalt** [comment]
Isn't the [virtual cylinder](https://github.com/otland/forgottenserver/blob/master/src/cylinder.h#L208) for that?

**Comment by TwistedScorpio** [comment]
@ranisalt I've attempted it, no error shows in the console, and no tile is created in the map (no item either).

I've added the following snippet to my local server:

```
const Position& position = getPosition(L, 3);
Tile* tile = g_game.map.getTile(position);
if (!tile) {
	tile = new DynamicTile(position.x, position.y, position.z);
	g_game.map.setTile(position, tile);
}

g_game.internalAddItem(tile, item, INDEX_WHEREEVER, FLAG_NOLIMIT);
```

It works, but isn't better "better code read ability" to simply create the tile if no tile exists (or rather add a parameter for it), rather than have the user have to type in Tile checks to then Game.createTile ?

**Comment by gugahoa** [comment]
I don't think so, but it's always open for discussion
I can't come up with a more reasonable argument other than the fact that Game.createTile is for that (creating tiles where at a position) and Game.createItem is for creating a item. Both have different uses and createItem shouldn't create a tile unless it's always used like this. If it's always used like this, then Game.createTile isn't useful since you can create a item with the tile id on a position (we would have two functions for the same logic)
