### ISSUE TITLE
Upgrade to Lua 5.2, some issues.

### ISSUE THREAD

**Issue by Colandus** [otland/forgottenserver#2082]
Hi. I'm attempting to update LuaJIT to use Lua 5.2. Works pretty good so far.

When compiling LuaJIT, the lua51.lib became only 27 kb compared to default one in TFS SDK which is ~1000kb, what am I missing?

I'm having one problem though. TFS crashes in specific cases, I believe related to addEvent & calling metamethods. So I'm wondering: **is the LuaJIT in the TFS SDK compiled with some type of safemode?**

I managed to crash my server using:

```addEvent(function() somenilvar:getStorageValue(1) end)```

Would also crash using any other variable type, boolean or int, e.g.

```
local n = 123
n:getStorageValue(1)
```
(Inside addEvent only though)

Which would normally not crash it. **This happens only in combination with /reload global. Only global, not talk (where the error is coming from) nor any other type. Doesn't matter if reload is before or after executing the code, but if I don't reload it won't crash (nor show any error).**

**EDIT: This may be my own problem. I'll debug it further. Maybe something else happened!**

@marksamman

**Comment by wgrriffel** [comment]
@Colandus actually tfs already use lua 5.2, at least on wiki [this](http://packages.ubuntu.com/precise/liblua5.2-dev) is the recommended package for linux systems on wiki.
tho im not aware of windows sdk version.

**Comment by Colandus** [comment]
@wgrriffel Hmm okay that's interesting. I'll check it out. On window's it's disable though. I managed to compile LuaJIT with 5.2 support on a separate project for windows, will try now in TFS:

**Comment by wgrriffel** [comment]
@Colandus why do you need 5.2? LuaJIT doesn't fully support any version better than 5.1.

**Comment by ranisalt** [comment]
Yes it would. You are passing userdata to addEvent, but that same userdata is deleted at the end of the **running** function and is unavailable to the addEvent callback. You should **never** pass userdata this way and it's documented somewhere.

Instead, pass safe values such as the id of a player instead of it's userdata, this way you just recover it with `Player(id)` inside the callback.

This is not something Lua 5.2 or any other version will ever "fix", as it's not a problem with the language itself but with your logic.

Do you see *any* advantages we would have in the [changelog for Lua 5.2](http://lua-users.org/wiki/LuaFiveTwo)?

**Comment by Colandus** [comment]
@ranisalt No, actually I'm not even passing userdata. I'm just passing nil (or a number or boolean) right away (just for testing). It wasn't a problem until I recompiled LuaJIT with support for some extended 5.2 support.

Actually I was just having an error in my code which I noticed only after upgrading due to the crash and debugging it. It will not crash normally and actually it won't crash at first instance, only after I use /reload (after having run that erroneous code). What I had done was accidentally called cid:getStorageValue(123) instead of player:getStorageValue. Nothing about passing userdata to addEvent or so. This is normally not a problem though.
