### ISSUE TITLE
Question about Dockerized TFS

### ISSUE THREAD

**Issue by Tarjei400** [otland/forgottenserver#2155]
Recently I am trying to get myself into contribution for TFS and OT in general. However I lack this nice feature. It's nice for me to develop with dockerized env since two commands and its up and running regardless PC you are working on. (If you have docker installed hehe)

 I made it a support for it already localy, but I would like to hear what do you guys think about it? Should I make a pull request?

**Comment by ranisalt** [comment]
You mean you created a Docker recipe to build TFS? It's a very nice idea indeed, especially because we could push forward to more recent versions of Ubuntu (i.e. 16.04) and using updated libs since Travis supports them via Docker.

I could add a how-to in the wiki if you upload the recipe to Docker Hub, but I don't feel it should be hosted on the repository.

**Comment by Tarjei400** [comment]
Yea I made it for purpose of testing my optimization for otclient, but I figure that might be nice, especially if we would add docker-compose to play

**Comment by ranisalt** [comment]
As I said, it should be separated from the repository (at most, maintaining `Dockerfile` here but no extra scripts) and freely linked on the wiki and forums.

**Comment by Tarjei400** [comment]
Okay I will make a pull-request and maybe you would be able to extract something out of it ?

**Comment by ranisalt** [comment]
Sure, do :)

**Comment by Tarjei400** [comment]
Its there : https://github.com/otland/forgottenserver/pull/2157/commits/bd1a90a6e918c5df940199a68ee5f392729f1d42
