### ISSUE TITLE
Compiling: CMake errors?

### ISSUE THREAD

**Issue by kito2** [otland/forgottenserver#2164]
Downloaded the repo, and then used the guide: https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu in order to compile and got this error.

Tried the same on different Linux (Debian an Ubuntu) and has the same problem. Compiling on Windows x64 works too, but I have this problem on Linux:

![image](https://cloud.githubusercontent.com/assets/21250744/22808093/0773fe8c-ef09-11e6-9f57-abb460dc5c5b.png)

Does any one knows what could be wrong?

**Comment by ranisalt** [comment]
Before line 41, which should be `add_executable(tfs ${tfs_SRC})`, can you add `message(${tfs_SRC})` and see if it prints anything?

**Comment by kito2** [comment]
Somehow fixed, just added a few lines to cmake lists.txt

**Comment by mkrukiew** [comment]
@kito2 I have the same problem, can you show me what you added to cmake lists.txt? please

**Comment by kito2** [comment]
![image](https://cloud.githubusercontent.com/assets/21250744/22829389/27031b84-ef81-11e6-92cd-03568158fa97.png)

That was my solution.

**Comment by ranisalt** [comment]
Since that line **is** present [on the file](https://github.com/otland/forgottenserver/blob/master/src/CMakeLists.txt#L78) since before you opened the issue and is not on the same line number, you are using a modified version of the code, not the one present in this repository. You should follow the issue template.
