### ISSUE TITLE
Missing feature (market doubt offer - red color)

### ISSUE THREAD

**Issue by Eternal-Scripts** [otland/forgottenserver#2271]
![maxresdefault](https://user-images.githubusercontent.com/20959344/27374485-5bb7bb0a-5642-11e7-9fd4-b27bf3e974e0.jpg)

I have tried many ways to make this happens in print but isn't working. I think is a calc in client where he receive price of offer statistics or any missing byte.

**Comment by joseluis2g** [comment]
About this, whan kind of messages are on red? Havent plyed tibia cip in a long time.

**Comment by thexamx** [comment]
Items which are red are calculated as the price of them is too high. I think is connected with "average price" in market.

**Comment by ranisalt** [comment]
Fetch the latest n (varying) offers in history, whatever is higher or lower than a deviation x is painted red.

**Comment by TheSumm** [comment]
The client does the calculation.
It seems like the statistics are sent: https://github.com/otland/forgottenserver/blob/f3f6d54e9bc8c205159b82fba43a8a42b05301bd/src/protocolgame.cpp#L1955-L1975

Your problem is probably that not enough transactions took place. The client requires like 10 or 20 transactions before it starts highlighting dubious offers.

**Comment by Eternal-Scripts** [comment]
I see in Flash Client the source code and is about 10 offers +- but i have tried put many offers with low price too.

Just try yourself and you will see.

**Comment by DSpeichert** [comment]
Seems like nothing to do here server-side.
