### ISSUE TITLE
Bugs in current auto stack system

### ISSUE THREAD

**Issue by nekiro** [otland/forgottenserver#2275]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
TFS:
https://i.gyazo.com/f6e7c309b7368102b12373494e3ed035.gif
Tibia:
https://i.gyazo.com/efac3a662f0a13d3333480edb0c737ae.gif

### Expected behaviour
When backpack is full, item should stack with first item in backpack that is not in count of 100

### Actual behaviour
It is not stacking (not even adding to the backpack), just returning value notenoughroom

**Comment by Codinablack** [comment]
I can confirm this, and I believe the three thumbs up means they confirm as well.

**Comment by ranisalt** [comment]
#1844 helps?

**Comment by thexamx** [comment]
@ranisalt its not related I think.
+ this pr is bugged.

**Comment by thexamx** [comment]
I have fixed this issue with:
in function:
`ReturnValue Container::queryAdd(int32_t index, const Thing& thing, uint32_t count,
		uint32_t flags, Creature* actor/* = nullptr*/) const`

This:
`if (index == INDEX_WHEREEVER && size() >= capacity() && !hasPagination()) {`
to:
`if (index == INDEX_WHEREEVER && size() >= capacity() && !hasPagination() && !isStackable()) {`

I'm not as much experienced, so let me know if it does not have any side-effects.

I tested it and all works correctly, you cannot add items when there is any to stack, otherwise it will stack even if full.

**Comment by thexamx** [comment]
Also another bug, if you are moving stackable to another container in backpack and there is another same type stackable to stack in the backpack, it should be moved to the container instead of stacking in current one.
