### ISSUE TITLE
LUA network message poll

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#2300]
I have this special question to @djarek and i'm making it here so more people can enjoy the answer for this question.
Suppose i have several functions like https://github.com/otland/forgottenserver/blob/master/data/lib/core/player.lua#L69 and i use them a lot in my server. Its an ideal to move a lot of systems to Lua and it may  have a lot custom packets that may be used a lot(otclient for a custom server for an example).
The current network stack(thanks @djarek) uses a poll that keeps a limited amount of memory that have been allocated by OutputMessage. Its prevents the system to allocate/deallocate the 20k bytes that are required by OutputMessage all time(and saving dispatcher cycles which is always good).
I'm thinking in building a lua pool that keeps a limited amount of NetworkMessage that will be used in functions like Player:sendExtendedOpcode. When the function needs a new NetworkMessage, the poll will check if there is any available in the list. If there is none, a new one will be created with a call to NetworkMessage(). When the function is done with the NetworkMessage, it will be added back to the list to prevent deallocation. I'm thinking how much performance i can gain with that. The dispatcher time is precious its why we must look for optimizations. At the same time, in my development computer it took 1 microsecond to allocate the new NetworkMessage/1-3 micro seconds to execute the whole luaNetworkMessageCreate/0-1 micro seconds to execute luaNetworkMessageDelete. We should also not forget about all the costs to calling the C++ function from lua. Its worth to build this lua poll if we want a server that handle a lot of players?

Ps: I'm using std::chrono::high_resolution_clock::now to calculate how look it takes to execute the allocation.

**Comment by ranisalt** [comment]
I am not really sure how should we test a huge load of something happening, in this case a lot of players playing, but if you manage to build such framework I'd be amused :+1: 

Adding things to Lua always adds flexibility which is good. If the time is not significantly changed it should not be a problem.

**Comment by djarek** [comment]
@HeavenIsLost 
2 years ago, when I was reworking the networking stack in TFS I measured the pooling allocator to be at least 10x faster(1 us vs ~10 us), on average, than malloc for allocations of this size (obviously this is heavily dependent on state of the heap). I expect the use of the custom allocator to improve performance in lua code by about the same factor. My observation was that the default allocator wasn't that bad when there was very little network communication going out, but was absolutely horrible when the heap was starting to get a little fragmented by all the little allocations everywhere in the server.

You should probably avoid writing a separate message pool for the lua subsystem and just reuse the mechanism used by the server. It uses a Lock-free stack to store messages so there is (close to) no lock contention and you might avoid some cache misses on the way by using "cache-warm" messages.

Please note that the message mechanism might change in the future. When we migrate to boost 1.66 we will probably switch to [this](http://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/ref/boost__beast__multi_buffer.html), with a custom allocator that reuses "pages" instead of whole messages (which might reduce memory otherwise wasted for large pools).

**Comment by djarek** [comment]
@HeavenIsLost 
Can this issue be closed?

**Comment by HeavenIsLost** [comment]
@djarek yes, thanks for the answer
