### ISSUE TITLE
Experience shared 

### ISSUE THREAD

**Issue by Larb1** [otland/forgottenserver#2303]
Experience shared:
Then you can group up and sit in the depo, be lower level, never atk, heal etc.. and gain xp.

PZloked:
Invalid

**Comment by thexamx** [comment]
No idea what you mean

**Comment by Larb1** [comment]
If i have party 5 membres share exp and 2 membres on dp afk they gain exp

**Comment by Larb1** [comment]
For reproduce Exp shared:
Enable Exp Party kill first monster and go pz

**Comment by Riverlance** [comment]
Tried here.

> Experience party
Works normally here. I got 2 players on party and enabled exp shared. Then I killed some monsters with both, sharing the exp between them. After that, I putted one player on PZ and, with the other I killed another monster. The party exp shared were disabled automatically. So, for me, it's okay.

> pzLocked
You are doing it wrong, @Larb1 
The pzLocked is the time for the error "You can not enter a protection zone after attacking another player.".
It means this is the time for when you attack the player (**not kill**), stops to attack and tries to enter on a protection zone.
If you are looking for the time that is for when you kill someone, use 'whiteSkullTime' instead (default is 15 * 60 * 1000 = 15 minutes).
If you are looking for the time that is for when decrease a frag after kill, use 'timeToDecreaseFrags'. If timeToDecreaseFrags is 24 * 60 * 60 * 1000, it will, for example, remove a red skull into 3 days, because red skull have 3 frags (3 * timeToDecreaseFrags = 3 * 24 * 60 * 60 * 1000 = 3 days).

**Comment by thexamx** [comment]
Everything is ok. These bugs does not exist in TFS.
You are not using TFS 1.3, if you got them.

**Comment by Larb1** [comment]
@thexamx its fake ?
https://uploaddeimagens.com.br/imagens/sem_titulo-png--22927
I'm using tfs 1.2 screen from source downloaded now

**Comment by thexamx** [comment]
@larb1
Looking at the image I cant find the bug, ofc exp will be shared when one character is in pz and other one is few sqms away killing monsters. If player that is killing monster will go away further it will not share the exp anymore. To get shared experience every party member need to hit monsters too.

**Comment by Larb1** [comment]
@thexamx  now what you see ?
https://uploaddeimagens.com.br/imagens/sem_titulo-png--22928
Is not a bug ?

**Comment by ranisalt** [comment]
Definitely not. While still on the idle timer, you can be wherever you want and you still will get exp. Wait a few more seconds and you will be considered idle and then you will not get exp.

**Comment by Riverlance** [comment]
@thexamx When I tried with 2 players, the party shared exp were disabled when a player was in PZ. But even if it does not disable, I don't think it would be considered as a bug, because of what @ranisalt said.

@Larb1 Your TFS version, according to your images, is 1.3, not 1.2. Also, try this: Be in party with other player and enable the shared experience. Let a player **WITHOUT KILLING ANY MONSTER AFTER ADDED ON THE PARTY** and **INSIDE A PZ**. Now, with the other player, go hunt. If both receives experience, we have a bug here. But if you kill a monster with the player that was on the PZ and get in to the PZ again, the other is hunting, and both receives experience, it's not a bug.

**Comment by Larb1** [comment]
@ranisalt yes correctly, after Xtime not get exp
Thanks @thexamx and @Riverlance
