### ISSUE TITLE
clang-format

### ISSUE THREAD

**Issue by DanielChabrowski** [otland/forgottenserver#2307]
Hello,
Not really an issue, just a question / proposal as I saw that @djarek did a little experiment with clang-format. Is there any particular reason why it was abandoned or are you guys open for PR with clang-format file.

Also, 21 commits since 19th of March, not much unfortunately.

**Comment by ranisalt** [comment]
That would be great. There's also clang-tidy and cppcheck.

> Is there any particular reason why it was abandoned or are you guys open for PR with clang-format file.

I think everybody is pretty busy, not more than that. Feel free to do it.

> Also, 21 commits since 19th of March, not much unfortunately.

See answer above 🤣

**Comment by Codinablack** [comment]
Just a small chime in on that 21 commits since 19th of march. I believe there are 86 open PR's right now, I get most of which aren't passing compatibility checks, and some who still need changes for other purposes, but there are currently 6 approved PR's just sitting there not merged that could be closed, I'm pretty sure each has an issue tied to it that could get closed as well.  One of which is marked as a bugfix and a milestone.

**Comment by ranisalt** [comment]
Please help us categorize and close/merge PRs. Most of the 86 are very old and aren't mergeable or were already fixed in other ways or even devs have gone completely away. 2 years ago we had ~75.

**Comment by Codinablack** [comment]
I understand that. I cannot possible close/merge simply because I do not have the push access. I shouldn't either, I barely know squat about C++. I apologize if I come off aggressive, insulting, or disrespectful.

 I'm not ungrateful either, I guess I am merely questioning the hesitation on actually merging already approved PR's. There are PR's sitting, waiting, and signed off on. I don't understand that, I have read the conversations and it seemed the consensus was that the PR was ready, for all 6 approved, yet the item custom attributes has been there forever. I thought it was decided that 1.3 was to have this feature, and the protobuf was to be pushed off till later big release. People need to see the help they do actually being applied. Time is relative.

Just in general, why are the ones approved sitting, who all has push access nowadays? I was out of the loop for awhile and I guess I just am not familiar with how things are being ran now.

**Comment by DanielChabrowski** [comment]
So... if we want clang-format, what are we going to do with Windows users?

find_program(CLANG_FORMAT NAMES "clang-format")
If you have clang-format added in PATH, then you call a custom cmake target and it works great. The problem is that Windows users don't use cmake and don't have LLVM installed. We can add the clang-format binary to the sdk. The sdk in itself is the problem as it doesn't contain things like pugixml libs, gmp libs are called "mpir" which results in errors during cmake configuration.

My proposal is to use git submodules and use cmake for compilation of required libraries and generating VS project files.

I can work on it tomorrow... today and also I'm open to any other solutions.

**Comment by ranisalt** [comment]
Just run clang-format on the CI and users should be fine.

**Comment by DanielChabrowski** [comment]
@ranisalt We can fail a build if clang-format actually changed something but I don't think we can apply changes from Travis back to github.

**Comment by ranisalt** [comment]
Yep, just fail and bail out. We could write a git hook to apply pre-commit.

**Comment by DanielChabrowski** [comment]
It seems that there is a way but it would require cooperation from @marksamman 

https://aniketpanse.in/2015/autodeploy-github-travis.html

**Comment by djarek** [comment]
I don't think it's necessary, [this is sufficient](https://github.com/otland/forgottenserver/blob/clang_format/verify-format.sh)
