### ISSUE TITLE
Chameleon & Convince creature bugs

### ISSUE THREAD

**Issue by DSpeichert** [otland/forgottenserver#2387]
This issue is to track:

>  I think the latest merge introduced two bugs, unable to use chameleon rune in your inventory & not notifying surrounding creatures about the master change (meaning that other creatures will not attack the creature you just convinced)

**Comment by nekiro** [comment]
Just tested this commit and cant seem to find any issue as these one listed above. I have summoned monster and convinced other with normal player, monster that got no master just killed my summon.

With chameleon rune, yes the issue is correct it does not work.
`local condition = Condition(CONDITION_OUTFIT)
condition:setTicks(200000)

function onCastSpell(creature, variant, isHotkey)
	local position = variant:getPosition()
	local item
	if position.x == CONTAINER_POSITION then
		local containerId = position.y - 64
		local container = creature:getContainerById(containerId)
		if container then
			item = container:getItem(position.z)
		end
	else
		item = Tile(variant:getPosition()):getTopDownItem()
	end

	if not item or item.itemid == 0 or not isMoveable(item.uid) then
		creature:sendCancelMessage(RETURNVALUE_NOTPOSSIBLE)
		creature:getPosition():sendMagicEffect(CONST_ME_POFF)
		return false
	end

	condition:setOutfit({lookTypeEx = item.itemid})
	creature:addCondition(condition)
	creature:getPosition():sendMagicEffect(CONST_ME_MAGIC_RED)
	return true
end`

**Comment by WibbenZ** [comment]
@nekiro That seems to work perfect, can you create a PR?

**Comment by WibbenZ** [comment]
@nekiro Now it works with items in your backpack but not items you are wearing.

**Comment by nekiro** [comment]
@WibbenZ Updated the code, now should work with all.

**Comment by WibbenZ** [comment]
@nekiro Now that seems to work, can you create a PR?
