### ISSUE TITLE
party shared

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2471]
https://github.com/otland/forgottenserver/blob/master/src/party.cpp#L441

The players are getting exp only by casting exura (without having to attack any monster), this is incorrect.

**Comment by jo3bingham** [comment]
The function you linked is only used to check if the player can share experience, hence the name `canUseSharedExperience`.

However, you're not wrong. When a player heals themselves, [Game::combatChangeHealth](https://github.com/otland/forgottenserver/blob/fa3e8741dc03c9d7fb8d0058cd62f04098fd573d/src/game.cpp#L3868) is called which triggers the target creature's [gainHealth](https://github.com/otland/forgottenserver/blob/fa3e8741dc03c9d7fb8d0058cd62f04098fd573d/src/creature.cpp#L767-L773) function:
```c++
// since the target is the player who casted the self-healing spell, target and attacker point to the same object
target->gainHealth(attacker, damage.primary.value);
```
```c++
void Creature::gainHealth(Creature* healer, int32_t healthGain)
{
    changeHealth(healthGain);
    if (healer) {
        healer->onTargetCreatureGainHealth(this, healthGain);
    }
}
```
Since the `healer` is a player, [Player::onTargetCreatureGainHealth](https://github.com/otland/forgottenserver/blob/fa3e8741dc03c9d7fb8d0058cd62f04098fd573d/src/player.cpp#L3461-L3478) is called. But the big issue is the `isPartner` check:
```c++
if (isPartner(tmpPlayer)) {
    party->updatePlayerTicks(this, points);
}
```
And, as you can see in `Player::isPartner`, it checks if both player's party pointers are the same (which they are in this case):
```c++
bool Player::isPartner(const Player* player) const
{
    if (!player || !party) {
        return false;
    }
    return party == player->party; // <- here's your problem
}
```
Simple fix, in the if statement in `Player::isPartner` check that the current player and the player argument aren't the same (since technically the player can't be a partner with itself):
```c++
if (!player || !party || player == this) {
    return false;
}
```

**Comment by DSpeichert** [comment]
Care to PR?
