### ISSUE TITLE
Critical damage 

### ISSUE THREAD

**Issue by karimadnan** [otland/forgottenserver#2726]
After some testing with critical damage it appears that critical is not working at all it's just an effect.

I used 100% critical chance with 100% critical damage and compared my damage with and without critical.

without crit on a 290 sorc with magic level 94
SD damage min:550 max:700

with crit equipped on same char
SD damage on crit max:700

**Comment by MillhioreBT** [comment]
In order to verify this, what I do is create a personalized magic with a fixed damage and thus be able to compare the critical damage correctly, it is not necessary to test for levels or skills, I only establish the damage at 1000 points and when the critical hit happens I get the expected result, in this case 2000 points.

Currently the critics system is working correctly, in the same way if I am wrong, I would like to know.

**Comment by karimadnan** [comment]
https://gyazo.com/eb9106b21dcef63c3ea5fba8f86749fb

https://gyazo.com/1049631891475c1a43632457d64ca306

**Comment by karimadnan** [comment]
> In order to verify this, what I do is create a personalized magic with a fixed damage and thus be able to compare the critical damage correctly, it is not necessary to test for levels or skills, I only establish the damage at 1000 points and when the critical hit happens I get the expected result, in this case 2000 points.
> 
> Currently the critics system is working correctly, in the same way if I am wrong, I would like to know.

**Comment by EPuncker** [comment]
I noticed this as well

**Comment by karimadnan** [comment]
False alarm it was my fault
