### ISSUE TITLE
Special Skills

### ISSUE THREAD

**Issue by Bauduen** [otland/forgottenserver#3107]
### Special Skills:
* Examples:
* Use a weapon that gives **10%** critical.
* Place the weapon in the slot(equip), go to items.xml and edit the critical weapon you are using for **11%**
* Now use **/reload items** and remove the weapon from the slot(unequip) you were using.
* Result: https://imgur.com/79VuoLV

**Comment by Xaekai** [comment]
You can embed small screenshots like that directly into your post. There is no need for a 3rd party service that may not work, for example, when clicked through the email notice sent out by Github for this issue.

![image](https://user-images.githubusercontent.com/594255/85983903-2a5d8f00-b99d-11ea-8f19-2cfbceab3fd3.png)

Anyway... **y**et **a**nother **p**roblem caused by **r**eloads. YARP.

**Comment by nekiro** [comment]
It's "impossible" to fix this issue, you are using reload in production, while you aren't meant to. To make this work you would need to literally iterate through all players online and remove their bonuses and force add new bonuses with new value.

**Comment by MillhioreBT** [comment]
> It's "impossible" to fix this issue, you are using reload in production, while you aren't meant to. To make this work you would need to literally iterate through all players online and remove their bonuses and force add new bonuses with new value. This most likely won't be fixed as (if I remember correctly), tfs devs plan on dropping reload.

This is possible to fix, simply the solution is cumbersome and ugly, I also agree that no such thing should be implemented, since the `reload` function is only for debugging purposes and not for immediate updates on a production server.
