### ISSUE TITLE
Error compiling in visual studio 2019

### ISSUE THREAD

**Issue by woeterman94** [otland/forgottenserver#3268]
(yes I followed the guide here: https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-%28vcpkg%29)

When trying to compile I get 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void std::_Normal_allocator_traits<_Alloc>::destroy<_Ty>(_Alloc &,_Ty *)': cannot convert argument 1 from '_Alloc' to '_Alloc &'	theforgottenserver	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\include\memory	1575
```

**Comment by gigastar** [comment]
I am compiling on VS2019 without any problems. Make sure you have followed everything correctly. To be sure are you compiling in x64 or x86?

**Comment by EPuncker** [comment]
I am compiling on VS2019 without any problems as well, and please use the issue template to provide all needed information

**Comment by nekiro** [comment]
Also using visual studio 2019 and it compiles just fine, issue most likely invalid, but let's see if we can get more info.

**Comment by MillhioreBT** [comment]
I'm always compiling multiple projects at the same time, none of them have caused me any problems, everything works great.

Your problem must be due to a bad installation of the SDK, if you do not find more useful information, my only suggestion is that you completely uninstall the visual studio and start a new installation, try to leave everything by default and not modify any parameter of the installation. once installed when you open the TFS project, select the solution in the solutions panel and right-click, you will probably get an option that suggests you install the necessary add-ons to compile this project.

**Comment by woeterman94** [comment]
Okay it worked! I had to change the compiler to use the v140 (visual studio 2015) toolset
