### ISSUE TITLE
Walking should NOT be canceled when doing any actions

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3411]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce
1. Walk into a straight line
2. Do any action (use item, use spell) while walking

### Expected behaviour
The character should perform the action and continue moving

### Actual behaviour
The character stops moving

### Reproduction environment
You can easily see the difference by testing cipbia and tfs

**Comment by EPuncker** [comment]
it is client sided 😢

**Comment by marmichalski** [comment]
You sure?
https://github.com/otland/forgottenserver/blob/48167ef5fee895f8195eebd82d15e6d01cece159/src/actions.cpp#L432-L435

**Comment by EPuncker** [comment]
> You sure?
> https://github.com/otland/forgottenserver/blob/48167ef5fee895f8195eebd82d15e6d01cece159/src/actions.cpp#L432-L435

yes, it still stops the walking, you can notice its client sided because on OTC it doesn't stop, while on cip client it does

**Comment by Codinablack** [comment]
This occurs in both useItem and useItemEx, to me, it makes no sense why stopWalk would be used in either case.

Is it truly preferred that one must stop for use of any and all items, I haven't played the original in a long time, but I always remembered being able to run while using items. 

The fact that in otlclient the player isn't stopped blows my mind, especially when I commented out both stopWalk() calls in useItem, and useItemEx, and it no longer interfered with auto walk, my character walked to where I clicked %100 of the time with 10.98 cip client, and without the comments, player stopped short everytime. 

Seems like an easy fix for the actions and to be able to close #3464 

I didn't see the stopWalk() called at all in spells, nor did I see any obvious or apparent reasons as to why it would stop you while casting except that perhaps most the spells check for position, maybe that has something to do with it.

Is there any reason we shouldn't implement the fix for #3464 by removing those lines? I assure you, it most definitely allows cip client to keep moving.

**Comment by Znote** [comment]
Submit pull request and let reviewers test suggested changes. If its a stable improvement it will get merged.

**Comment by EPuncker** [comment]
last time I tested this after @marmichalski pointed that out, the character still stopped walking (note: using arrows to walk, not mapclick)

**Comment by Codinablack** [comment]
I had no issues with walking with arrows, and my walk being cancelled from using items, at most, when using the arrows and using an item, the character would redirect, to move close enough to use item. I did not test with the flag "allowfaruse" at all though.
