### ISSUE TITLE
Spells combat:getTargets addEvent Error: onTargetCreature not found.

### ISSUE THREAD

**Issue by robpot95** [otland/forgottenserver#3500]
### Before creating an issue, please ensure:
- [x ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ x] This issue is reproducible without changes to the C++ code in this repository

### Expected behaviour
No error, should print target name

### Actual behaviour
Getting error and no print, only happens when you delay your combat:getTargets, if you use it directly then it works but not delayed for some reason.
`[Warning - CallBack::loadCallBack] Event onTargetCreature not found.`

This version throws error and does not work.
```
local combat = Combat()
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_FIRE)
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
combat:setArea(createCombatArea(AREA_CIRCLE3X3))

function delayCombat(id, variant)
	local player = Player(id)
	if player then
		for _, target in ipairs(combat:getTargets(player, variant)) do
			print(target:getName())
		end

		return combat:execute(player, variant)
	end
end

local spell = Spell(SPELL_INSTANT)
function spell.onCastSpell(player, variant)
	addEvent(delayCombat, 2000, player.uid, variant)
	return true
end

spell:id(1)
spell:name("Test")
spell:words("test")
spell:isSelfTarget(true)
spell:blockWalls(true)
spell:register()
```

While this version works:
```
local combat = Combat()
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_FIRE)
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
combat:setArea(createCombatArea(AREA_CIRCLE3X3))

function onTargetCreature(player, target)
	print(target:getName())
end

combat:setCallback(CALLBACK_PARAM_TARGETCREATURE, "onTargetCreature")

function delayCombat(id, variant)
	local player = Player(id)
	if player then
		return combat:execute(player, variant)
	end
end

local spell = Spell(SPELL_INSTANT)
function spell.onCastSpell(player, variant)
	addEvent(delayCombat, 2000, player.uid, variant)
	return true
end

spell:id(1)
spell:name("Test")
spell:words("test")
spell:isSelfTarget(true)
spell:blockWalls(true)
spell:register()
```

**Comment by MillhioreBT** [comment]
The first code should not even give the error you mention, since there is nothing related
`[Warning - CallBack::loadCallBack] Event onTargetCreature not found.` <- There is no code snippet that makes use of any call that requires this callback

You are just confused, I recommend that you review the scripting learning book so that you can learn to create your own scripts without any problem! For now this should be closed, as it is not a problem nor is it a suggestion.

Assuming you wrongly copy and paste the code here, I'll explain what the problem is:
```lua
function onTargetCreature(player, target)
	print(target:getName())
end

combat:setCallback(CALLBACK_PARAM_TARGETCREATURE, "onTargetCreature")
```

When you set a callback to a combat, this will look for the function with the given name in the global environment and then save it in a reference table for later use, while the function is removed from the environment so as not to interfere with other scripts, in this case: `onTargetCreature`, According to your error in the console, it is telling you that it cannot find the function with the name: `onTargetCreature` and that is all your problem, in the second script that you publish, the function is declared.
