### ISSUE TITLE
Buggy normal doors in TFS 1.3

### ISSUE THREAD

**Issue by Alkenix** [otland/forgottenserver#3520]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Place a stone wall in RME and use the normal door tool in the bottom left corner to place a door in it.
2. Save the Map and start your server.
3. "The door is locked." -> But it's an normal to open design one.

### Expected behaviour
Ppl should be able to open the door.

### Actual behaviour
"The door is locked."

### Environment
Newest TFS 1.3 from here.
RME 3.7 and 3.2
Version: 10.98

**Comment by Alkenix** [comment]
Check this in global.lua.. it's still a broken mix of closed doors in locked and locked in closed doors.
I'm working on a clean up right now.

**Comment by Alkenix** [comment]
Checked it again.. Loaded the lastest files already and still have this bug.
When I open an door with an lock-sprite it opens up..
But when I try to open an normal door it switched item ID and says It is locked".

The bug is in my opinion still there and needs to be fixed.

**Comment by EPuncker** [comment]
not a tfs bug, but RME file outdated, will open a fix for it there today

**Comment by BahamutxD** [comment]
> not a tfs bug, but RME file outdated, will open a fix for it there today

Can we reconsider this?

Taking TFS map as an example.

![image](https://user-images.githubusercontent.com/6182531/127738015-5ee52903-8b64-4b58-8d04-8525f43caba7.png)

This door is supposed to be closed and unlocked -  it always been as it's the path to the boat.

![image](https://user-images.githubusercontent.com/6182531/127738163-c3a0f132-1216-41f7-b68b-d0948f722ace.png)

Since https://github.com/otland/forgottenserver/commit/86aecd6d9d578191938a03bb20b243367786674e this door is part of the lockedDoors in global.lua.

Every door in that lockedDoors list points to the first of the 2 avaiable doors for every type of normal doors. IE

![image](https://user-images.githubusercontent.com/6182531/127738083-27c70e43-74a4-4e88-a878-7704a73ebd67.png)

![image](https://user-images.githubusercontent.com/6182531/127738094-0ac9a5fd-f34c-4bd4-b999-90bd7bc58b2b.png)

The outcome of this is that every single map will have their normal doors swapped. Doors that are supposed to be locked will be unlocked and doors that are supposed to just be closed will be closed and locked.

The fix could just be to swap locked to closed doors in global.lua
