### ISSUE TITLE
Skill multiplier cant be lower than 1.1 in data/XML/vocations.xml

### ISSUE THREAD

**Issue by Znote** [otland/forgottenserver#3577]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Change skill multiplier of Knight from 1.1 to 1.0
2. Login with a fresh knight with 10 fist,club,sword,axe skill
3. Attack monsters and get blood hit

### Expected behaviour

You should gain skills roughly 10% faster than normal
Lower value should mean faster skillgain, as the skilltries pool should be reduced

### Actual behaviour

You dont gain any skills at all. 

Some tests:
Club multiplier: 1.0. 30 hits, 0% skillgain from 11 -> 12
Sword multiplier: 1.1: 10 hits, 54% skillgain from 11 -> 12
Axe multiplier: 5.0: 15 hits, 12% skillgain from 11 -> 12

### Environment

Ubuntu 20.04

### Reproduction environment

Change these multiplier values to 1.0 and try to train with a knight:
https://github.com/otland/forgottenserver/blob/2515744010225cfbcbebecb215649dc02bcdf983/data/XML/vocations.xml#L45-L48

Shielding is untouched, and will go up, melee skills are stuck without progress.

**Comment by marmichalski** [comment]
Well, it can be lower than 1.1, it just can't be 1.0 as that means 0% skill-gain I believe?

**Comment by gesior** [comment]
Skill **multiplier** must be high enough, to make 'next skill' require more 'tries' than previous:
https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L444-L451
This code checks, if next skill tries number is higher than previous, because otherwise algorithm could go into infinite loop. Like it does on TFS 0.4, when player get max. skill (18kkkkkk tries!). Maybe getting 18kkkkkk tries wasn't often, but if you make knight with 100 sword skill and switch it's vocation to sorc, it will calculate that you have to do 18kkkkkk+ tries to get next skill and server may go into infinite loop (freez forever).

Skill bases are here:
https://github.com/otland/forgottenserver/blob/master/src/vocation.cpp#L180
```
static const uint32_t skillBase[SKILL_LAST + 1] = {50, 50, 50, 50, 30, 100, 20};
```
So in case of melee attack skills, minimum multiplier is 1.02, because with this value we get 50 * 1.02 = 51. 51 > 50 = valid value
For distance it must be 1.04, as 30 * 1.04.

To make it work with lower **multiplier** values, you must increase **skillBase** value or make players start (create character) with higher skill values like 30 or 50.

**Comment by Znote** [comment]
ohh my, thank you. So issue is invalid, its not a bug. Just not very intuitive. :P 
Since this is an exponential curve, I wonder what value I need to replace 1.1 with to get 20-30% faster skills.

Compared 60 sword fighting at 0.08, with 60 shielding at 1.10
by the time I trained 30% sword, I trained 11% shielding. 
so a .02 difference was over 250% faster. 
But I suck at exponential curves math. <.< I guess for every skill gained, the difference between 1.1 and 1.08 becomes exponentially larger.

**Comment by gesior** [comment]
@Znote 
Total hits to get skills 11 - 100 with base 50 (melee skills) and **1.10** multiplier:
https://www.wolframalpha.com/input/?i=sum+50*1.10%5Ej%2C+j%3D11+to+100
50 skill: 63k tries
100 skill: ~7.5kk tries

Total hits to get skills 11 - 100 with base 50 (melee skills) and **1.08** multiplier:
https://www.wolframalpha.com/input/?i=sum+50*1.08%5Ej%2C+j%3D11+to+100
50 skill: 30k tries
100 skill: ~1.5kk tries

So advancing from 10 to 50 will be 2 times faster, but 10 to 100 will be 5 times faster with 1.08 in place of 1.10.
