### ISSUE TITLE
(minor enhancement) spell words

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3630]
### Explanation of what you want to do that is currently impossible
be able to check for incorrect spell words between items and spells (lets say spells.xml is the correct one)

### Desired functionality
check if **key="runeSpellName" value="adori not bla bla"** in items.xml matches spells.xml **words="adori blabla bla"** value, if not display a console error with information such as id and spell word.

**Comment by Zbizu** [comment]
While we're at it, itemType class doesn't have a way to read words from runes. Because of that onLook can't be rewritten to lua fully without using ugly hacks (like interpreting and caching items.xml to lua memory). The spell system doesn't allow retreiving words for rune spells either (you can Spell(runeId), but you can't call :words() getter on it).

**Comment by EPuncker** [comment]
@emil92b that is not possible unless we do very ugly hacks, like adding spell ID to both files, otherwise the code doesn't have any way to know which spell words belong to specific spell so it can compare... in other words: machine learning 😄
