### ISSUE TITLE
new event onRotateItem

### ISSUE THREAD

**Issue by lucasgrizante** [otland/forgottenserver#3976]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the C++ code in this repository

This is not a bug, but a feature request.
I'd like a new event "onRotateItem" that will be executed after player rotates an object.

**Why?** 
I'm trying to make a statue in my temple using the new Podium feature. I could limit players to not move/edit it using already available events (onMoveItem, onPodiumRequest and onPodiumEdit), yet, they can rotate it (and I think there's no way without editing sources to limit that).

**Comment by EPuncker** [comment]
this is pretty interesting because podium is the only item that rotates, but actually doesn't rotate. we only rotate outfit direction on it 🤔 

we should really add a house check here:
https://github.com/otland/forgottenserver/blob/e20bc717ce2b1ec78d914f7860926a2cd82cfeb6/src/game.cpp#L2379

to allow rotating a podium only if it is located inside a house tile

but accordingly to the code I referenced, you could just add an unique ID to podium and it will become not rotatable
