### ISSUE TITLE
Questions regarding recent changes in copyright notices

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#4052]
#3969 and #3994 made some changes bound with the license

I am developing a fork and currently merging and manually adjusting changes from the upstream (ie. this repository master branch) and I have some questions:

\- do I have your permission to update the copyright notices in my fork to match these from the master branch?
(speaking specifically of a heavily customized branch "master" in my fork)

\- are authors and contributors/developers the same thing (they're listed in AUTHORS file)?
\-- Does that make me a (partial) copyright holder?
\-- Doesn't that invalidate some points of the gpl (eg. the point that forbids changing the license to other than gpl)?

\- hypothetically speaking, is there a person who can legally license tfs with something other than gpl (ie. the "legal owner" of tfs)? The repo itself is a fork of opentibia server, but was modified by a lot of people and more than 50% of the original code got changed so should I ask opentibia server creators instead?

note: I do not intend to violate the copyright. I'm doing my best to give proper credit to everyone (hence why I'm asking for a permission to update my repo with the contents of these commits). I'm just curious about the implications of these two commits.

**Comment by marksamman** [comment]
> - do I have your permission to update the copyright notices in my fork to match these from the master branch?
> (speaking specifically of a heavily customized branch "master" in my fork)
> - are authors and contributors/developers the same thing (they're listed in AUTHORS file)?
> -- Does that make me a (partial) copyright holder?

Yes, yes and yes.

> -- Doesn't that invalidate some points of the gpl (eg. the point that forbids changing the license to other than gpl)?

The license cannot be changed without permission of all contributors as they have made the contribution under GPL and they did not sign a CLA saying otherwise. Even if changed, it would not affect already GPL-licensed copies, only future copies that are provided under a different license. The license has not been changed from GPL, it is still GPL-licensed. The purpose of the referenced pull requests was to fix the attribution as I am not the sole contributor.

> - hypothetically speaking, is there a person who can legally license tfs with something other than gpl (ie. the "legal owner" of tfs)? The repo itself is a fork of opentibia server, but was modified by a lot of people and more than 50% of the original code got changed so should I ask opentibia server creators instead?

No, you can always re-license your own contributions, but your past contributions also remain GPL-licensed and can be used in accordance with the GPL-license by those who chose not to accept your new license.

**Comment by Zbizu** [comment]
That answered my questions, thank you.
