### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by xmish** [otland/forgottenserver#4340]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Run tfs
2. login
3. wait

### Expected behaviour

MySQL connection is stable.

### Actual behaviour

```sql
2023-03-05 18:41:28 [Error - mysql_real_query] Query: SELECT `id`, `amount`, `price`, `itemtype`, `player_id`, `sale` FROM `market_offers` WHERE `created` <= 1675446088
2023-03-05 18:41:28 Message: Lost connection to MySQL server during query
2023-03-05 19:39:40 admin has logged out.
2023-03-05 19:39:40 [Error - mysql_real_query] Query: DELETE FROM `players_online` WHERE `player_id` = 1
2023-03-05 19:39:40 Message: Lost connection to MySQL server during query
```
### Environment

Docker (Windows 10 x64):
- mysql-server: `mysql/mysql-server:latest`
- tfs: master 2aea2638f6612d368843fc0f8acb4748ca3333e9 (alpine:3.16.2)

### Reproduction environment

Besides that I noticed same issue on my Debian 10 machine where I host it directly. Before migration from ~1.4 (with patches) it worked fine.

Example:
```sql
[Error - mysql_real_query] Query: SELECT `reason`, `expires_at`, (SELECT `name` FROM `players` WHERE `id` = `banned_by`) AS `name` FROM `ip_bans` WHERE `ip` = INET6_ATON('::ffff:xx.xxx.xxx.xxx')
Message: Lost connection to MySQL server during query
```

Note:
- I do not have any special MYSQL settings, it's default mysql config (same for docker and same for debian host)

**Comment by Mau005** [comment]
I think this error is more critical, it happened to me with the server running for more than 20 days, and at the end it kills the process in ubuntu and it can't connect, making everything go very slow.

One of the solutions that I have been able to come up with, that is, it does not crash all the time, is to create a user in the DB with @127.0.0.1
and remove bind_addres from mysql configuration, even if the problem persists. but not immediately and being 6 hours minimum

If you have more information, please tell me, since I have the server running for more than 1 month and I don't know what to do with the problem.

The query that has a problem is not one, but can be any within TFS since the main error is that it loses connection with the DB.

I have had problems registering new users
Removing User from Online List
o Simply remove an item from the depot.

**Comment by Mau005** [comment]
previous solved
this problem is due to low ram or a script crashes with a query, so i try to notice,
had the same problem.
Solutions:
comment out bind-addres from mysql's my.conf
create a user in mysql name@127.0.0.1
performing these steps, I noticed that the error persisted but the time where it occurred increased
So I increased the RAM and CPU of the VPS more and solved, there were no more crashes.
I think this is because of the VPS that have only 1 thread and it fails because it cannot execute perelism, although it is my theory.

Greetings
