### ISSUE TITLE
The future of compatibility

### ISSUE THREAD

**Issue by IntinteDAO** [otland/forgottenserver#4353]
Welcome.

I wanted to ask what the future of forgottenserver compatibility looks like. From what I suspect, there is a switch of the supported client from 10.98 to 12.xx happening right now. And from various statements I gather that there will no longer be support for "classic Tibia", or am I wrong?

**Comment by EPuncker** [comment]
the switch has already happened, 10.98 will be kept only on 1.4.x branch, master branch is the newer version and we will try to keep updating it as long as cip updates keep coming out

btw 1.4.x has no maintainer

**Comment by IntinteDAO** [comment]
@EPuncker I just noticed this and preferred to ask, because I wanted to build a project around Tibia 10.x (LibreTibia, i.e. all open, open source projects about Tibia, in one source).

I now have to think what to do next XD

Closing

**Comment by luanluciano93** [comment]
Hello. I've always wondered if it wouldn't be feasible for the TFS project to fill in the boxes and support the older and more used versions. He would work with all audiences and the number of problems reported and possible solutions would be much greater. OTC works that way. TFS could also work and be more flexible because it is losing space for some forks and every day fewer people use it. It's just the humble opinion of a very grateful lover of the project.

**Comment by IntinteDAO** [comment]
@luanluciano93 That's why I test OpenCoreMMO :P They plans to have backward compatibility
