### ISSUE TITLE
Missing Files from Release 1.4.2 in Master

### ISSUE THREAD

**Issue by Underewarrr** [otland/forgottenserver#4519]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Clone Repo
2. Use files from release to start server
3. Alot files missing between master and release 1.4.2

### Expected behaviour
Open server using master (current impossible)

### Actual behaviour
The behavior, where the master branch is not updated with all the files and content from the release, indicates that there might be a problem with the synchronization of changes between branches or the merging process.

**Comment by Underewarrr** [comment]
Looks like have more conflicts.
Using source from master and release from 1.4.2.
These erros occours.
![image](https://github.com/otland/forgottenserver/assets/74227915/ce672b90-08d1-4c66-8468-8d24c59d7bae)

**Comment by JimmyTmm** [comment]
monsters.xml provided in "Forgotten-server Master" files has 1166 monsters.
compared to "Forgotten-server 1.4.2 - Latest" version, there is only 741 monsters.
impossible to use the "Master" version "monsters.xml" file in Remere's Map Editor because there is no "creatures.xml" file which has all the 1166 monsters included. So you end up having Creature names in Creature pallette which are empty and if you place a spawn, client will crash when you walk in the game towards the spawn because there is missing a creature.
