### ISSUE TITLE
exura gran mas res heals monsters too

### ISSUE THREAD

**Issue by att3** [otland/forgottenserver#666]
exura gran mas res heals monsters too
It only should heal players.

**Comment by raymondtfr** [comment]
@marksamman I guess this can be closed now, since it has been the way @att3 requested -- if I'm not mistaken in a PR by @WibbenZ . Besides that, I made a tiny improvement by adding a bool ``healMonsters = false`` so users can decide whether to use it or not.
https://github.com/otland/forgottenserver/blob/master/data/spells/scripts/healing/mass%20healing.lua#L15
