### ISSUE TITLE
Missing item attributes [$100]

### ISSUE THREAD

**Issue by Crypton33** [otland/forgottenserver#998]
# Missing Item Attributes

Hello,
There are some attributes that have been implemented in TFS 0.4, but that aren't added in 1.0.
### Attribute list

Increasing power of melee / magic / healing:

```
increasemeleevalue
increasemeleepercent

increasemagicvalue
increasemagicpercent

increasehealingvalue
increasehealingpercent
```

Reflect system - something like absorb system, but the attacker gets some of the damage back:

```
reflectpercentall
reflectpercentelements
reflectpercentmagic
reflectpercentenergy
reflectpercentfire
reflectpercentearth
reflectpercentice
reflectpercentholy
reflectpercentdeath
reflectpercentlifedrain
reflectpercentmanadrain
reflectpercentdrown
reflectpercentphysical
reflectpercenthealing
```

For every reflect type:

```
reflectchanceall
reflectchanceelements
reflectchance...
```

Extra attributes for absorbing player / monster damage, could be useful for creating tank items:

```
absorbpercentmonsters
absorbpercentplayers
```

Also it should be possible to set those attributes by using item:setAttribute(...)
# Bounty

Unfortunately I'm kinda busy, so I won't have time to work on it.
Fortunately Znote gave idea for using **Bountysource**, so I'm setting $65 bounty for adding those atributes.
##

**Comment by whitevo** [comment]
The above attributes on post 1 are quite irrelevant since we can manipulate them already in LUA trough creaturescripts.

What we can't do in LUA is change the container slot amount.

**Comment by WibbenZ** [comment]
Correct but note the "manipulate" word.
To me that script seems like a hack insted of doing it hard coded.

**Comment by WibbenZ** [comment]
@Crypton33, (Znote - can't tag him) and @marksamman 
Im thinking about fixing this, but how do you guys want the XML code to look like?
Should we use the 0.x one (we will have to break the if statments down if we compile with visual studio, but we keep compatibility)
Or should we use a new one, that makes it look cleaner?
If you ask me we should do something new, since 1.x has never had item attributes so there kinda is no compatibility to retain.

This is what I did last night, looks cleaner to me atleast.
```
<attribute key="reflection" value="allelements">
	<attribute key="chance" value="100" />
	<attribute key="percent" value="100" />
</attribute>

<attribute key="reflection" value="energy">
	<attribute key="chance" value="100" />
	<attribute key="percent" value="100" />
</attribute>
```

It will take up more space, but as I said (to me) it looks alot cleaner compared to this:
```
reflectpercentelements
reflectpercentenergy
``` 

Still need to rewrite / add the other things you wrote about.
But these 2 below I can't find them in either (0.4) r3777 or r3884, are they even used or did you want them implemented?

````
increasemeleevalue
increasemeleepercent
```

**Comment by Znote** [comment]
@marksamman Do you have any guidelines which should be followed to help a developer create an acceptable pull request?

**Comment by marksamman** [comment]
I'm not sure what the best way would be to implement this, and PR's with new features will have to wait until after the 1.2 release anyway. I'd rather see community effort around issues in the 1.2 milestone as the release is already long overdue.

**Comment by TheGodOfLegends** [comment]
My team have been working on this issue for several days, tonight we have finily finished, tested and working 100%
contact me by facebook (James Hazeth) or skype, Heretic.Legends
to get access to the complied .exe  or src codes

**Comment by JSkalskiSBG** [comment]
I wrote these attributes/features for WibbenZ.
@WibbenZ 
If you still have it, you can release it. You paid for it - it's your code now.

@marksamman 
It's not possible to compile it in Visual Studio, because in "void Items::parseItemNode(const pugi::xml_node& itemNode, uint16_t id)":
https://github.com/otland/forgottenserver/blob/master/src/items.cpp#L539
are already 102 switch cases.
After adding all reflections and new attributes code reached over 128 switch cases. There is hard-coded limit of switch cases in VS C++ compiler. I read about it in some bug report to VS 2003 (yes, 2003!) and there were answers that they won't fix it. Even with many post from users that refreshed that bug report in 2013 and 2014, they decided to not change it.

// gesior at work

**Comment by ranisalt** [comment]
@JSkalskiSBG you could split the cases into several functions insite the cpp file - they will be inlined anyway.

**Comment by Zbizu** [comment]
is the problem with switch cases still occuring in 2017 and newer versions of visual studio?
